# Generated by Django 5.0.3 on 2024-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mein_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('discription', models.TextField()),
                ('brand', models.CharField(choices=[('a', 'Arong'), ('e', 'Easy'), ('z', 'Zara Man'), ('s', 'Sara'), ('b', 'Black Brids')], max_length=2)),
                ('cetagory', models.CharField(choices=[('P', 'Pent'), ('s', 'saree'), ('k', 'Lehanga'), ('j', 'Jersy'), ('sh', 'Shirt')], max_length=2)),
                ('product_img', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
